### ISSUE TITLE
Feature Request: Return stdout

### ISSUE THREAD

**Issue by theironrobin** [BOJIT/btmgmt#4]
i am requesting a command_str function that returns tuple[int, str] instead of just the error code.

**Comment by BOJIT** [comment]
Hi, I haven't looked into this repo in a while, but I did have plans to implement that syntax into the library when I wrote it. I didn't need it at the time, but if there is a use case I'll have a look at incorporating it :)

**Comment by theironrobin** [comment]
Thank you!

**Comment by BOJIT** [comment]
Hi, I've added the `command_str` functionality. See the updated readme for syntax. Currently this will redirect both `stdout` and `stderr` to the returned string (not that I've ever managed to get any output on `stderr` while running the `btmgmt` tool).

Let me know if this works for you and I'll close the issue.

Also, if you end up using this library on a hardware platform that is not under my 'tested on' list, let me know and I'll add it. I've only ever used this library on a Raspberry Pi, so would be interested to know if there are any build/runtime issues on other platforms.

Cheers,
James

**Comment by theironrobin** [comment]
Thanks, James, it looks like exactly what I need, so I will close this ticket. However, in practice, it seems to block the UI thread of my GTK app, not sure why, probably due to my incompetent programming.

**Comment by BOJIT** [comment]
Fair enough - the functions will block for as long as the btmgmt command takes to execute, which can be a little time, especially if you are doing something like scanning. I've never done any GTK stuff, so not entirely sure, but it's probably worth handling the btmgmt call in a separate thread and doing some inter-thread communication or async/await. Best of luck with the app!
